services:
  kotlinapp:
    container_name: gymmonitorlite
    image: gymmonitorlite:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    environment:
      # Environment variables should be loaded from a .env file in this directory
      DB_URL: ${DB_URL}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}