services:
  kotlinapp:
    container_name: gymmonitorlite
    image: gymmonitorlite:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    env_file: # Loads all variables from .env
      - .env
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}