package com.leonardlau.gymmonitor.gymmonitorlite.entity

import jakarta.persistence.*

/**
 * Represents a gym club.
 *
 * @property id Unique identifier for the club.
 * @property name Name of the gym club.
 * @property code Unique code required for users to join this club.
 * @property address Physical address of the club.
 */
@Entity
@Table(name = "clubs")
data class Club(
    // Primary key. Value is automatically generated by the database.
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Int = 0,

    @Column(nullable = false)
    val name: String,

    @Column(nullable = false, unique = true)
    val code: String,

    @Column(nullable = false)
    val address: String
)