package com.leonardlau.gymmonitor.gymmonitorlite.entity

import jakarta.persistence.*

/**
 * Represents a location where classes are held.
 *
 * @property id Unique identifier for the location.
 * @property club The club this location belongs to.
 * @property name Display name of the location (e.g. “Yoga Studio").
 */
@Entity
@Table(name = "locations")
data class Location(
    // Primary key. Value is automatically generated by the database.
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Int = 0,

    // Foreign key reference to the Club entity. Represents which club this location belongs to.
    @ManyToOne
    @JoinColumn(name = "club_id", nullable = false)
    val club: Club,

    @Column(nullable = false)
    val name: String  // e.g., "Yoga Studio", "Boxing Room"
)
