package com.leonardlau.gymmonitor.gymmonitorlite.entity

import jakarta.persistence.*

/**
 * Represents a membership plan available for users to choose when signing up to a club.
 * (For simplicity, only recurring memberships are currently supported (members pay 
 * automatically every x days))
 *
 * @property id Unique identifier for the membership plan.
 * @property club The club offering the plan.
 * @property name Name of the plan.
 * @property billingPeriodDays Number of days between payments (e.g. 7 for weekly).
 * @property classesPerWeek Maximum number of classes the user can attend each week.
 * @property priceCents Cost of the plan in cents.
 * @property active Boolean that determines whether or not the plan is currently active.
 */
@Entity
@Table(name = "membership_plans")
data class MembershipPlan(
    // Primary key. Value is automatically generated by the database.
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Int = 0,

    // Foreign key reference to the Club entity. Represents which club this membership plan belongs to.
    @ManyToOne
    @JoinColumn(name = "club_id", nullable = false)
    val club: Club,

    @Column(nullable = false)
    val name: String,

    @Column(name = "billing_period_days", nullable = false)
    val billingPeriodDays: Int, // e.g. 7 for weekly, 14 for fortnightly

    @Column(name = "classes_per_week", nullable = false)
    val classesPerWeek: Int,

    @Column(name = "price_cents", nullable = false)
    val priceCents: Int, // e.g. 100 for $1, 1000 for $10

    @Column(nullable = false)
    val active: Boolean = true // true if the plan is currently active, false otherwise
)
