package com.leonardlau.gymmonitor.gymmonitorlite.entity

import jakarta.persistence.*
import java.time.Instant

/**
 * Represents a user’s visit to a gym club.
 *
 * @property id Unique identifier for the visit.
 * @property member The member who visited.
 * @property club The club visited.
 * @property scannedAt Timestamp of when the user scanned in their visit.
 */
@Entity
@Table(name = "visits")
data class Visit(
    // Primary key. Value is automatically generated by the database.
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Int = 0,

    // Foreign key reference to the User entity. Represents the member User who made the visit.
    @ManyToOne
    @JoinColumn(name = "member_id", nullable = false)
    val member: User,

    // Foreign key reference to the Club entity. Represents the club visited.
    @ManyToOne
    @JoinColumn(name = "club_id", nullable = false)
    val club: Club,

    @Column(name = "scanned_at", nullable = false)
    val scannedAt: Instant = Instant.now() // Automatically assigns the current date
)
