package com.leonardlau.gymmonitor.gymmonitorlite.entity

import jakarta.persistence.*
import java.time.Instant

/**
 * Represents a booking for a gym class made by a member.
 *
 * @property id Unique identifier for the booking.
 * @property gymClass The class that was booked.
 * @property member The member who made the booking.
 * @property bookedAt When the booking was made.
 * @property status Status of the booking (e.g. "BOOKED", "CANCELLED", "COMPLETED").
 */
@Entity
@Table(name = "bookings")
data class Booking(
    // Primary key. Value is automatically generated by the database.
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Int = 0,

    // Foreign key reference to the GymClass entity. Represents the gym class being booked.
    @ManyToOne
    @JoinColumn(name = "gym_class_id", nullable = false)
    val gymClass: GymClass,

    // Foreign key reference to the User entity. Represents the member User who made the booking.
    @ManyToOne
    @JoinColumn(name = "member_id", nullable = false)
    val member: User,

    @Column(name = "booked_at", nullable = false)
    val bookedAt: Instant = Instant.now() // Automatically assigns the current date

    @Column(nullable = false)
    val status: String,  // e.g., "BOOKED", "CANCELLED", "COMPLETED"
)
