package com.leonardlau.gymmonitor.gymmonitorlite.entity

import jakarta.persistence.*
import java.time.LocalDateTime

/**
 * Represents a scheduled gym class.
 *
 * @property id Unique identifier for the class.
 * @property location Where the class is held.
 * @property staff The staff member responsible for teaching the class.
 * @property name Name or title of the class.
 * @property description Description of the gym class.
 * @property startTime Date and time when the class starts.
 * @property endTime Date and time when the class ends.
 * @property maxCapacity Maximum number of attendees.
 */
@Entity
@Table(name = "gym_classes")
data class GymClass(
    // Primary key. Value is automatically generated by the database.
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Int = 0,

    // Foreign key reference to the Location entity. Represents the location where this class is held.
    @ManyToOne
    @JoinColumn(name = "location_id", nullable = false)
    val location: Location,

    // Foreign key reference to the User entity. Represents which staff member is teaching the class.
    @ManyToOne
    @JoinColumn(name = "staff_id", nullable = false)
    val staff: User,

    @Column(nullable = false)
    val name: String,

    @Column(nullable = false)
    val description: String,

    @Column(name = "start_time", nullable = false)
    val startTime: LocalDateTime, // timestamp

    @Column(name = "end_time", nullable = false)
    val endTime: LocalDateTime, // timestamp

    @Column(name = "max_capacity", nullable = false)
    val maxCapacity: Int
)
